---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-server4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server4
  template:
    metadata:
      labels:
        app: web-server4
    spec:
      containers:
        - name: web-server-con
          image: httpd
