---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-server3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server3
  template:
    metadata:
      labels:
        app: web-server3
    spec:
      containers:
        - name: web-server-con
          image: 526174677628.dkr.ecr.ap-northeast-1.amazonaws.com/ripecr:latest
