---
apiVersion: v1
kind: Service
metadata:
  name: web-server3-sv-lb
spec:
  selector:
    app: web-server3
  type: LoadBalancer
  ports:
    - name: java-app
      port: 8080
      targetPort: 80
      protocol: TCP
