---
apiVersion: v1
kind: Service
metadata:
  name: web-server4-sv-lb
spec:
  selector:
    app: web-server4
  type: LoadBalancer
  ports:
    - name: java-app
      port: 80
      targetPort: 80
      protocol: TCP
